// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartMeal.Infrastructure.Data;

#nullable disable

namespace SmartMeal.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260926145430_AddModule6MealPlannerAndGrocery")]
    partial class AddModule6MealPlannerAndGrocery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartMeal.Domain.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tôm, cua, ốc, mực",
                            Name = "Hải sản (Seafood)"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lạc và chế phẩm từ lạc",
                            Name = "Đậu phộng (Peanuts)"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sữa bò, phô mai, bơ",
                            Name = "Sữa động vật (Dairy)"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Trứng gà, trứng vịt",
                            Name = "Trứng (Eggs)"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bánh mì, mì ý bột mì",
                            Name = "Gluten (Lúa mì)"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Đậu phụ, sữa đậu nành",
                            Name = "Đậu nành (Soy)"
                        });
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.DiaryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsGrams")
                        .HasColumnType("double precision");

                    b.Property<double>("FatGrams")
                        .HasColumnType("double precision");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NutritionDiaryId")
                        .HasColumnType("uuid");

                    b.Property<double>("ProteinGrams")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<double>("ServingSize")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("NutritionDiaryId");

                    b.HasIndex("RecipeId");

                    b.ToTable("DiaryItems");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.GroceryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EstimatedPriceVnd")
                        .HasColumnType("numeric");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("GroceryItems");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.HealthProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<double>("BMI")
                        .HasColumnType("double precision");

                    b.Property<double>("BMR")
                        .HasColumnType("double precision");

                    b.Property<double>("CurrentWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double>("DailyCaloriesTarget")
                        .HasColumnType("double precision");

                    b.Property<double>("DailyCarbsTargetGrams")
                        .HasColumnType("double precision");

                    b.Property<double>("DailyFatTargetGrams")
                        .HasColumnType("double precision");

                    b.Property<double>("DailyProteinTargetGrams")
                        .HasColumnType("double precision");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<double>("TDEE")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HealthProfiles");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AllergyId")
                        .HasColumnType("integer");

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedPriceVnd")
                        .HasColumnType("numeric");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("double precision");

                    b.Property<double>("FiberPer100g")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("double precision");

                    b.Property<double>("SodiumMgPer100g")
                        .HasColumnType("double precision");

                    b.Property<double>("SugarPer100g")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("PlanDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.MedicalCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicalConditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hạn chế đường và carbs hấp thu nhanh",
                            Name = "Tiểu đường (Diabetes)"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hạn chế purin (nội tạng, thịt đỏ, hải sản)",
                            Name = "Gout (Axit Uric cao)"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chế độ ăn giảm muối Natri (DASH)",
                            Name = "Cao huyết áp (Hypertension)"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hạn chế mỡ bão hòa và cholesterol",
                            Name = "Mỡ máu cao (Dyslipidemia)"
                        });
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.NutritionDiary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionDiaries");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.OtpVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CaloriesPerServing")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsPerServing")
                        .HasColumnType("double precision");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FatPerServing")
                        .HasColumnType("double precision");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<double>("ProteinPerServing")
                        .HasColumnType("double precision");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.RecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTags");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Eat Clean"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Keto"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thuần Chay (Vegan)"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tăng Cơ (High Protein)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nhanh Gọn (< 15 phút)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tiết Kiệm Ngân Sách"
                        });
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPro")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.UserAllergy", b =>
                {
                    b.Property<Guid>("HealthProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("AllergyId")
                        .HasColumnType("integer");

                    b.HasKey("HealthProfileId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.ToTable("UserAllergies");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.UserCondition", b =>
                {
                    b.Property<Guid>("HealthProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("MedicalConditionId")
                        .HasColumnType("integer");

                    b.HasKey("HealthProfileId", "MedicalConditionId");

                    b.HasIndex("MedicalConditionId");

                    b.ToTable("UserConditions");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.UserFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.WeightHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HealthProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("HealthProfileId");

                    b.ToTable("WeightHistories");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.DiaryItem", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId");

                    b.HasOne("SmartMeal.Domain.Entities.NutritionDiary", "NutritionDiary")
                        .WithMany("Items")
                        .HasForeignKey("NutritionDiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.Navigation("Ingredient");

                    b.Navigation("NutritionDiary");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.GroceryItem", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");

                    b.HasOne("SmartMeal.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.HealthProfile", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.User", "User")
                        .WithOne("HealthProfile")
                        .HasForeignKey("SmartMeal.Domain.Entities.HealthProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId");

                    b.Navigation("Allergy");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.MealPlan", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Domain.Entities.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.NutritionDiary", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.User", "User")
                        .WithMany("NutritionDiaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.RecipeTag", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Domain.Entities.Tag", "Tag")
                        .WithMany("RecipeTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.UserAllergy", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.Allergy", "Allergy")
                        .WithMany("UserAllergies")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Domain.Entities.HealthProfile", "HealthProfile")
                        .WithMany("UserAllergies")
                        .HasForeignKey("HealthProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("HealthProfile");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.UserCondition", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.HealthProfile", "HealthProfile")
                        .WithMany("UserConditions")
                        .HasForeignKey("HealthProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Domain.Entities.MedicalCondition", "MedicalCondition")
                        .WithMany("UserConditions")
                        .HasForeignKey("MedicalConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthProfile");

                    b.Navigation("MedicalCondition");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.UserFavorite", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Favorites")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartMeal.Domain.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.WeightHistory", b =>
                {
                    b.HasOne("SmartMeal.Domain.Entities.HealthProfile", "HealthProfile")
                        .WithMany("WeightHistories")
                        .HasForeignKey("HealthProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthProfile");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.Allergy", b =>
                {
                    b.Navigation("UserAllergies");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.HealthProfile", b =>
                {
                    b.Navigation("UserAllergies");

                    b.Navigation("UserConditions");

                    b.Navigation("WeightHistories");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.MedicalCondition", b =>
                {
                    b.Navigation("UserConditions");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.NutritionDiary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.Tag", b =>
                {
                    b.Navigation("RecipeTags");
                });

            modelBuilder.Entity("SmartMeal.Domain.Entities.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("HealthProfile");

                    b.Navigation("MealPlans");

                    b.Navigation("NutritionDiaries");
                });
#pragma warning restore 612, 618
        }
    }
}
