export const ENDPOINTS = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    google: '/auth/google',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    resendOtp: '/auth/resend-otp',
    verifyOtp: '/auth/verify-otp',
    resetPassword: '/auth/reset-password',
    changePassword: '/auth/change-password',
    me: '/auth/me',
    profile: '/auth/profile',
    avatar: '/auth/avatar',
    account: '/auth/account',
  },
  /** Dữ liệu cá nhân của người dùng (BR-271). */
  me: {
    data: '/me/data',
  },
  healthProfile: {
    base: '/healthprofile',
    survey: '/healthprofile/survey',
    profile: '/healthprofile',
    weightLog: '/healthprofile/weight-log',
    weightHistory: '/healthprofile/weight-history',
  },
  meta: {
    allergies: '/meta/allergies',
    medicalConditions: '/meta/medical-conditions',
    tags: '/meta/tags',
  },
  nutritionDiary: {
    log: '/nutritiondiary/log',
    logBatch: '/nutritiondiary/log/batch',
    daily: '/nutritiondiary/daily',
    weeklyProgress: '/nutritiondiary/weekly-progress',
    item: (id: string) => `/nutritiondiary/items/${id}`,
    water: '/nutritiondiary/water',
    waterEntry: (id: string) => `/nutritiondiary/water/${id}`,
  },
  foods: {
    list: '/foods',
    byId: (id: string) => `/foods/${id}`,
    barcode: (code: string) => `/foods/barcode/${code}`,
    favorite: (id: string) => `/foods/${id}/favorite`,
  },
  healthSync: {
    stepsAndCalories: '/health-sync/steps-and-calories',
    dailySummary: '/health-sync/daily-summary',
  },
  recipes: {
    list: '/recipes',
    detail: (id: string) => `/recipes/${id}`,
    byId: (id: string) => `/recipes/${id}`,
    suggestByPantry: '/recipes/suggest-by-pantry',
    favorite: (id: string) => `/recipes/${id}/favorite`,
    favorites: '/recipes/favorites',
    collections: '/recipes/collections',
    collection: (id: string) => `/recipes/collections/${id}`,
    collectionItems: (id: string) => `/recipes/collections/${id}/items`,
    collectionItem: (collectionId: string, recipeId: string) =>
      `/recipes/collections/${collectionId}/items/${recipeId}`,
  },
  mealPlanner: {
    week: '/mealplanner/week',
    assign: '/mealplanner/assign',
    delete: (id: string) => `/mealplanner/${id}`,
    byId: (id: string) => `/mealplanner/${id}`,
    complete: (id: string) => `/mealplanner/${id}/complete`,
    autoGenerate: '/mealplanner/auto-generate',
  },
  grocery: {
    list: '/grocery',
    generateFromPlan: '/grocery/generate-from-plan',
    items: '/grocery/items',
    checkAll: '/grocery/items/check-all',
    check: (id: string) => `/grocery/items/${id}/check`,
    itemCheck: (id: string) => `/grocery/items/${id}/check`,
    delete: (id: string) => `/grocery/items/${id}`,
    item: (id: string) => `/grocery/items/${id}`,
    clearChecked: '/grocery/clear-checked',
  },
  ai: {
    quota: '/ai/quota',
    snapAndTrack: '/ai/snap-and-track',
    fridgeScanner: '/ai/fridge-scanner',
    voiceLog: '/ai/voice-log',
    checkSafety: '/ai/check-safety',
  },
  gamification: {
    pet: '/gamification/pet',
    streak: '/gamification/streak',
    challenges: '/gamification/challenges',
    joinChallenge: (id: string) => `/gamification/challenges/${id}/join`,
    badges: '/gamification/badges',
    equipCostume: (id: string) => `/gamification/costumes/${id}/equip`,
    unequipCostume: '/gamification/costumes/equipped',
  },
  subscription: {
    plans: '/subscription/plans',
    checkout: '/subscription/create-checkout-session',
    createCheckoutSession: '/subscription/create-checkout-session',
    activateMock: '/subscription/activate-mock',
    status: '/subscription/status',
    transactions: '/subscription/transactions',
    cancel: '/subscription/cancel',
  },
} as const;
